### ISSUE TITLE
新版本更新后连不上搜索了

### ISSUE THREAD

**Issue by LovelyGuYiMeng** [hezhijie0327/chat-plugin-searxng-search#50]
搜索返回结果为空
![image](https://github.com/user-attachments/assets/0922743f-e4e1-4463-b417-eeef30e4971b)

**Comment by hezhijie0327** [comment]
诶 没复现出来诶... 重新 Build 下？

![image](https://github.com/user-attachments/assets/e7ba9f42-b159-45e7-a27c-552935f3176e)

**Comment by LovelyGuYiMeng** [comment]
discord说
